site_name: new_template_workshop
nav:
  - Home: index.md

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      project_name: new_template_workshop
      handlers:
        python:
          options:
            docstring_style: numpy